/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.climbsafe.application;

import java.sql.Date;

import ca.mcgill.ecse.climbsafe.javafx.fxml.ClimbSafeFxmlView;
import ca.mcgill.ecse.climbsafe.javafx.fxml.controllers.EquipmentPageController;
import ca.mcgill.ecse.climbsafe.model.ClimbSafe;
import ca.mcgill.ecse.climbsafe.persistance.ClimbSafePersistence;
import javafx.application.Application;

public class ClimbSafeApplication {
  private static ClimbSafe climbSafe;

  public static void main(String[] args) {
    getClimbSafe();
    Application.launch(ClimbSafeFxmlView.class, args);
  }

  public static ClimbSafe getClimbSafe() {
    if (climbSafe == null) {
    	ClimbSafePersistence.setFilename("ClimbSafeDemo.data");
      climbSafe = ClimbSafePersistence.load();
    }
    
    return climbSafe;
  }
}
